# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: vpc

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: vpc_test

production:
  adapter: postgresql
  encoding: unicode
#  username:
#  password:
  pool: 5
  host: db
  database: vpc_prod